baseurl = "https://chrisjburns.com"

title = "chrisjburns"

# theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsCodefences = true
pygmentsStyle = "lovelace"

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Chris Burns"
    keywords = "blog,developer,personal"
    info = "Software engineer"
    avatarurl = "images/avatar.jpg"
    # footercontent = "Site coming soon..."

    dateformat = "January 2, 2006"
    hideCredits = true
    hideCopyright = true
    since = 2019

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ChrisJBurns/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/chris-j-burns/"

[[menu.main]]
    name = "BLOG"
    weight = 1
    url = "posts/"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "chrisjburns.com"
URL = "s3://chrisjburns.com?region=eu-west-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID =	"E1TU1GPR0AAJ1Q"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true